// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class ChatMessage;
@class ChatMessage_Builder;

@interface ChatMessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ChatMessage : PBGeneratedMessage {
@private
  BOOL hasTopic_:1;
  BOOL hasBody_:1;
  NSString* topic;
  NSString* body;
}
- (BOOL) hasTopic;
- (BOOL) hasBody;
@property (readonly, retain) NSString* topic;
@property (readonly, retain) NSString* body;

+ (ChatMessage*) defaultInstance;
- (ChatMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChatMessage_Builder*) builder;
+ (ChatMessage_Builder*) builder;
+ (ChatMessage_Builder*) builderWithPrototype:(ChatMessage*) prototype;

+ (ChatMessage*) parseFromData:(NSData*) data;
+ (ChatMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ChatMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ChatMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ChatMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChatMessage_Builder : PBGeneratedMessage_Builder {
@private
  ChatMessage* result;
}

- (ChatMessage*) defaultInstance;

- (ChatMessage_Builder*) clear;
- (ChatMessage_Builder*) clone;

- (ChatMessage*) build;
- (ChatMessage*) buildPartial;

- (ChatMessage_Builder*) mergeFrom:(ChatMessage*) other;
- (ChatMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChatMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTopic;
- (NSString*) topic;
- (ChatMessage_Builder*) setTopic:(NSString*) value;
- (ChatMessage_Builder*) clearTopic;

- (BOOL) hasBody;
- (NSString*) body;
- (ChatMessage_Builder*) setBody:(NSString*) value;
- (ChatMessage_Builder*) clearBody;
@end

