### Generated by rprotoc. DO NOT EDIT!
### <proto file: chat_message.proto>
# package com.foo;
# 
# option java_package = "com.foo.tutorial";
# option java_outer_classname = "ChatMessageProtos";
# 
# message ChatMessage {
# required string topic = 1;
# required string body = 2;
# }
require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Com
  module Foo
    ::Protobuf::OPTIONS[:"java_package"] = "com.foo.tutorial"
    ::Protobuf::OPTIONS[:"java_outer_classname"] = "ChatMessageProtos"
    class ChatMessage < ::Protobuf::Message
      defined_in __FILE__
      required :string, :topic, 1
      required :string, :body, 2
    end
  end
end